use phf::{Map, phf_map};

use crate::lexer::Token::{self, *};

pub static KEYWORDS: Map<&'static str, &[Token]> = phf_map! {
    "i32" => &[Signed, Int],
    "i64" => &[Signed, Long],
    "u32" => &[Unsigned, Int],
    "u64" => &[Unsigned, Long],
    "int" => &[Int],
    "long" => &[Long],
    "void" => &[Void],
    "signed" => &[Signed],
    "unsigned" => &[Unsigned],
    "return" => &[Return],
    "if" => &[If],
    "else" => &[Else],
    "goto" => &[Goto],
    "do" => &[Do],
    "while" => &[While],
    "for" => &[For],
    "switch" => &[Switch],
    "case" => &[Case],
    "default" => &[Default],
    "break" => &[Break],
    "continue" => &[Continue],
    "static" => &[Static],
    "extern" => &[Extern],
};

pub static TWO_CHAR_OPS: Map<&'static str, Token> = phf_map! {
    "<<" => LeftShift,
    ">>" => RightShift,
    "&&" => LogicalAnd,
    "||" => LogicalOr,
    "==" => Equal,
    "!=" => NotEqual,
    "<=" => LessEqual,
    ">=" => GreaterEqual,
    "+=" => AddAssign,
    "-=" => SubtractAssign,
    "*=" => MultiplyAssign,
    "/=" => DivideAssign,
    "%=" => RemainderAssign,
    "&=" => BitwiseAndAssign,
    "^=" => BitwiseXorAssign,
    "|=" => BitwiseOrAssign,
    "++" => Increment,
    "--" => Decrement,
};

pub static ONE_CHAR_OPS: Map<u8, Token> = phf_map! {
    b'(' => OpenParen,
    b')' => CloseParen,
    b'{' => OpenBrace,
    b'}' => CloseBrace,
    b';' => Semicolon,
    b'~' => Tilde,
    b'-' => Hyphen,
    b'+' => Plus,
    b'*' => Asterisk,
    b'/' => Slash,
    b'%' => Percent,
    b'&' => Ampersand,
    b'^' => Caret,
    b'|' => Pipe,
    b'!' => Not,
    b'<' => LessThan,
    b'>' => GreaterThan,
    b'=' => Assign,
    b'?' => QuestionMark,
    b':' => Colon,
    b',' => Comma,
};
